"use client";
import { FormEvent, ReactNode, useRef, useState } from "react";
export const inputClass = "w-full rounded-lg border border-[#121212]/10 bg-white px-3.5 py-2.5 text-sm text-[#121212] outline-none transition-colors focus:border-[#8BA888]";
export const labelClass = "mb-1.5 block text-[10px] font-bold uppercase tracking-[0.22em] text-[#121212]/45";
export const panelClass = "rounded-xl border border-[#121212]/10 bg-white/90 p-6 shadow-sm";
export async function readJson(response: Response) { const text = await response.text(); if (!text) return {} as any; try { return JSON.parse(text); } catch { return { error: text } as any; } }
export function money(value: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value); }
export function formatDateTime(value: string) { const match = value.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/); if (!match) return value; const [, year, month, day, hourValue, minute] = match; const hour = Number(hourValue); const monthName = new Date(Number(year), Number(month) - 1, 1).toLocaleDateString("en-IN", { month: "short" }); return `${Number(day)} ${monthName} ${year}, ${hour % 12 || 12}:${minute} ${hour >= 12 ? "PM" : "AM"}`; }
export function formatLongDate(value: string, emptyValue = "Not set") { if (!value) return emptyValue; const [year, month, day] = value.slice(0, 10).split("-").map(Number); if (!year || !month || !day) return value; const teen = day % 100 >= 11 && day % 100 <= 13; const suffix = teen ? "th" : day % 10 === 1 ? "st" : day % 10 === 2 ? "nd" : day % 10 === 3 ? "rd" : "th"; const monthName = new Date(year, month - 1, 1).toLocaleDateString("en-IN", { month: "long" }); return `${day}${suffix} ${monthName} ${year}`; }
export function formatLongDateTime(value: string) { if (!value) return ""; const parsed = new Date(value); if (Number.isNaN(parsed.getTime())) return value; const localDate = `${parsed.getFullYear()}-${String(parsed.getMonth() + 1).padStart(2, "0")}-${String(parsed.getDate()).padStart(2, "0")}`; const time = parsed.toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit", hour12: true }); return `${formatLongDate(localDate)}, ${time}`; }
export function formatDateTimesInText(value: string) { return value.replace(/\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2})?/g, (match) => match.includes("T") ? formatLongDateTime(match) : formatLongDate(match)); }
export function SectionLoading({ label = "Loading data" }: { label?: string }) { return <div className="flex min-h-64 items-center justify-center" role="status" aria-label={label}><span className="h-9 w-9 animate-spin rounded-full border-2 border-[#121212]/15 border-t-[#121212]" /></div>; }
export function PageHeading({ title, description }: { title: string; description: string }) { return <div className="mb-6"><h3 className="text-2xl font-semibold">{title}</h3><p className="mt-1 text-sm text-[#121212]/55">{description}</p></div>; }
export function SimpleForm({ onSubmit, submitLabel, children }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void | Promise<void>; submitLabel: string; children: ReactNode }) { const submittingRef = useRef(false); const [submitting, setSubmitting] = useState(false); async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (submittingRef.current) return; submittingRef.current = true; setSubmitting(true); try { await onSubmit(event); } finally { submittingRef.current = false; setSubmitting(false); } } return <form onSubmit={handleSubmit} className={panelClass}><div className="grid gap-5">{children}<button type="submit" disabled={submitting} aria-busy={submitting} className="mt-1 rounded-lg bg-[#121212] px-4 py-3.5 text-xs font-bold uppercase tracking-[0.22em] text-white disabled:cursor-not-allowed disabled:opacity-60">{submitting ? "Saving..." : submitLabel}</button></div></form>; }
export function TextField({ name, label, type = "text", required = false, onValueChange, error }: { name: string; label: string; type?: string; required?: boolean; onValueChange?: (value: string) => void; error?: string }) { return <div><label htmlFor={name} className={labelClass}>{label}</label><input id={name} name={name} type={type} required={required} onChange={onValueChange ? (event) => onValueChange(event.target.value) : undefined} aria-invalid={Boolean(error)} aria-describedby={error ? `${name}-error` : undefined} className={inputClass} />{error && <p id={`${name}-error`} className="mt-1.5 text-xs font-medium text-red-700">{error}</p>}</div>; }
export function SelectField({ name, label, options, required = false, onValueChange }: { name: string; label: string; options: string[]; required?: boolean; onValueChange?: (value: string) => void }) { return <div><label htmlFor={name} className={labelClass}>{label}</label><select id={name} name={name} required={required} defaultValue={required ? "" : undefined} onChange={onValueChange ? (event) => onValueChange(event.target.value) : undefined} className={inputClass}>{required && <option value="" disabled>Select {label}</option>}{options.map((option) => <option key={option}>{option}</option>)}</select></div>; }
export function CheckboxGroup({ name, label, options }: { name: string; label: string; options: Array<{ value: string; detail: string }> }) { return <fieldset><legend className={labelClass}>{label}</legend><div className="grid max-h-48 gap-2 overflow-y-auto rounded-lg border border-[#121212]/10 bg-white p-3">{options.length ? options.map((option) => <label key={option.value} className="flex cursor-pointer items-center gap-3 rounded-md px-2 py-2 hover:bg-[#121212]/5"><input type="checkbox" name={name} value={option.value} className="h-4 w-4 accent-[#5F7F5C]" /><span className="min-w-0"><span className="block truncate text-sm font-medium">{option.value}</span><span className="block truncate text-xs text-[#121212]/50">{option.detail}</span></span></label>) : <p className="text-sm text-[#121212]/50">No active employees available.</p>}</div></fieldset>; }
export function StatusPill({ value }: { value: string }) { return <span className="w-fit rounded-full bg-[#8BA888]/15 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.18em] text-[#5F7F5C]">{value}</span>; }
export function Row({ title, meta, pills, extra }: { title: string; meta: string; pills: string[]; extra?: ReactNode }) { return <div className="grid gap-3.5 rounded-lg border border-[#121212]/10 bg-[#F7F7F5] p-5 md:grid-cols-[1fr_auto] md:items-center"><div><p className="font-semibold">{title}</p><p className="text-xs text-[#121212]/55">{meta}</p>{extra && <div className="mt-2">{extra}</div>}</div><div className="flex flex-wrap gap-2">{pills.filter(Boolean).map((pill) => <StatusPill key={pill} value={pill} />)}</div></div>; }
export function NotificationRow({ item }: { item: { id: string; title: string; body: string; type: string } }) { return <div className="rounded-lg border border-[#121212]/10 bg-[#F7F7F5] p-5"><div className="mb-2 flex flex-wrap items-center gap-2"><StatusPill value={item.type} /><p className="font-semibold">{item.title}</p></div><p className="text-sm text-[#121212]/60">{formatDateTimesInText(item.body)}</p></div>; }
