export type SeoEntry = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  intro: string;
  challenges: readonly string[];
  capabilities: readonly string[];
  outcomes: readonly string[];
};

export const industries: readonly SeoEntry[] = [
  { slug: "fuel-retail", title: "Fuel Retail Software", eyebrow: "Industry · Fuel retail", description: "Offline-first fuel retail software for billing, shifts, wet-stock, credit, reconciliation, and audit-ready reporting.", intro: "Fuel operations need speed at the counter and control after every shift. We design one accountable workflow across sales, stock, credit, and reconciliation—even when connectivity is unreliable.", challenges: ["Connectivity cannot interrupt billing", "Wet-stock and book-stock require traceability", "Shift handovers create reconciliation risk"], capabilities: ["Offline-first billing and sync", "Shift, tank, credit, and stock controls", "Exception reporting and audit history"], outcomes: ["Faster frontline work", "More reliable shift closure", "Clearer management visibility"] },
  { slug: "logistics", title: "Logistics Operations Software", eyebrow: "Industry · Logistics", description: "Custom logistics software for dispatch, fleet workflows, proof of delivery, exceptions, and operational visibility.", intro: "Logistics software must coordinate movement, people, evidence, and exceptions without adding administrative drag. We model the operating flow before selecting interfaces or integrations.", challenges: ["Status is fragmented across teams", "Exceptions are discovered too late", "Proof and reconciliation remain manual"], capabilities: ["Dispatch and assignment workflows", "Proof-of-delivery capture", "Exception queues and operational dashboards"], outcomes: ["Fewer status handoffs", "Earlier exception response", "Traceable delivery evidence"] },
  { slug: "manufacturing", title: "Manufacturing Workflow Software", eyebrow: "Industry · Manufacturing", description: "Manufacturing software for production workflows, inventory traceability, quality checks, and maintenance controls.", intro: "Production systems are useful only when they reflect the factory floor. We connect material movement, work stages, quality evidence, and exceptions through explicit operational states.", challenges: ["Manual production updates reduce visibility", "Traceability breaks between stages", "Quality evidence is difficult to retrieve"], capabilities: ["Production and work-order workflows", "Material and batch traceability", "Quality checks and maintenance records"], outcomes: ["Current production status", "Stronger traceability", "Actionable quality history"] },
  { slug: "enterprise-saas", title: "Enterprise SaaS Engineering", eyebrow: "Industry · Enterprise SaaS", description: "Enterprise SaaS product engineering with multi-tenancy, permissions, billing, observability, and integrations.", intro: "We engineer SaaS products as long-lived operating systems: tenant isolation, permissions, commercial rules, support tooling, and observability are designed into the architecture.", challenges: ["Early architecture limits later scale", "Permissions grow without a coherent model", "Support lacks operational evidence"], capabilities: ["Multi-tenant architecture", "Identity, roles, billing, and integrations", "Observability and support operations"], outcomes: ["Safer customer growth", "Predictable product operations", "Lower support ambiguity"] },
  { slug: "custom-software", title: "Custom Software Development", eyebrow: "Industry · Custom software", description: "Purpose-built custom software for complex business rules, integrations, and operational workflows.", intro: "Custom software is justified when the operation is differentiated, controls matter, or generic tools create permanent workarounds. We turn those constraints into a maintainable product boundary.", challenges: ["Generic tools distort the workflow", "Manual bridges create hidden cost", "Legacy integrations constrain change"], capabilities: ["Discovery and domain modelling", "Custom applications and APIs", "Migration, deployment, and maintenance"], outcomes: ["Software fitted to the operation", "Fewer manual workarounds", "Explicit long-term ownership"] },
  { slug: "ai-automation", title: "AI Automation Systems", eyebrow: "Industry · AI automation", description: "Human-supervised AI automation for documents, support, knowledge workflows, and operational decisions.", intro: "Useful AI automation needs bounded tasks, reliable context, review paths, and measurable failure handling. We design automation around operational controls rather than demonstrations.", challenges: ["Unbounded outputs create risk", "Knowledge is fragmented or stale", "Automation lacks review and audit paths"], capabilities: ["Document and knowledge workflows", "Human approval and escalation", "Evaluation, logging, and guardrails"], outcomes: ["Reduced repetitive work", "Faster assisted decisions", "Visible automation quality"] },
];

export const technologies: readonly SeoEntry[] = [
  { slug: "nextjs-react", title: "Next.js & React Engineering", eyebrow: "Technology · Web platforms", description: "Production Next.js and React engineering for fast, accessible, maintainable web applications.", intro: "We use React and Next.js where server rendering, product interfaces, and a coherent full-stack web model create clear operational value.", challenges: ["Rendering choices affect speed and SEO", "Client state becomes difficult to govern", "Design systems drift across features"], capabilities: ["App Router and server rendering", "Accessible component systems", "Performance and bundle analysis"], outcomes: ["Fast product interfaces", "Search-ready content", "Maintainable frontend boundaries"] },
  { slug: "nodejs-api", title: "Node.js API Engineering", eyebrow: "Technology · Backend", description: "Node.js backend and API engineering for secure workflows, integrations, and SaaS products.", intro: "Backend services should encode business invariants, authorization, and failure behavior explicitly. We design APIs around domain boundaries and operating evidence.", challenges: ["Business rules leak across endpoints", "Integrations fail without recovery paths", "Authorization becomes inconsistent"], capabilities: ["REST and event-driven services", "Integration and retry design", "Validation, authorization, and testing"], outcomes: ["Clear service contracts", "Recoverable integrations", "Consistent security boundaries"] },
  { slug: "postgresql-data", title: "PostgreSQL & Data Systems", eyebrow: "Technology · Data", description: "PostgreSQL data modelling, reporting, migrations, and performance engineering for operational software.", intro: "Operational reliability starts with a data model that protects invariants and supports the questions the business must answer.", challenges: ["Schemas mirror screens instead of operations", "Reporting competes with transactions", "Migrations become high-risk events"], capabilities: ["Relational domain modelling", "Query and index optimisation", "Migration and reporting architecture"], outcomes: ["Reliable business records", "Predictable query performance", "Safer schema evolution"] },
  { slug: "offline-first-pwa", title: "Offline-First & PWA Engineering", eyebrow: "Technology · Resilience", description: "Offline-first application and PWA engineering with local persistence, synchronization, and conflict handling.", intro: "Offline-first is a data and recovery architecture, not a cache switch. We design local writes, synchronization, conflict policy, and operational visibility together.", challenges: ["Connectivity is intermittent", "Conflicts can silently corrupt intent", "Sync failures are hard to diagnose"], capabilities: ["Local-first data workflows", "Queued synchronization and retries", "Conflict policy and sync observability"], outcomes: ["Continuity during outages", "Controlled reconciliation", "Visible synchronization health"] },
  { slug: "cloud-devops", title: "Cloud & DevOps Engineering", eyebrow: "Technology · Delivery", description: "Cloud deployment, CI/CD, observability, environment, and operational readiness engineering.", intro: "Deployment is part of product design. We define repeatable environments, release controls, telemetry, recovery, and ownership before production pressure exposes gaps.", challenges: ["Releases depend on manual knowledge", "Environment drift hides defects", "Incidents lack useful telemetry"], capabilities: ["CI/CD and release gates", "Container and cloud deployment", "Logs, metrics, alerts, and rollback"], outcomes: ["Repeatable releases", "Faster diagnosis", "Reduced deployment risk"] },
  { slug: "applied-ai", title: "Applied AI Engineering", eyebrow: "Technology · Intelligence", description: "Applied AI engineering for retrieval, classification, extraction, assistants, and controlled automation.", intro: "We treat model output as an uncertain system input. Evaluation, context quality, permissions, fallbacks, and human review define whether the feature is production-ready.", challenges: ["Demos do not establish reliability", "Sensitive context requires controls", "Quality changes as inputs evolve"], capabilities: ["Retrieval and knowledge systems", "Structured extraction and classification", "Evaluation, guardrails, and review queues"], outcomes: ["Measurable model quality", "Safer production use", "Maintainable AI workflows"] },
];

export const resources = [
  { slug: "offline-first-systems-guide", kind: "Guide", title: "A Practical Guide to Offline-First Systems", description: "Architecture decisions for local writes, synchronization, conflicts, recovery, and observability.", readTime: "12 min", sections: ["When offline-first is justified", "Local data and write ownership", "Synchronization and retry policy", "Conflict resolution", "Observability and support"] },
  { slug: "operational-software-discovery", kind: "Guide", title: "Discovery for Operational Software", description: "How to map users, invariants, exceptions, evidence, and acceptance criteria before implementation.", readTime: "9 min", sections: ["Map the real operation", "Identify invariants and exceptions", "Define roles and evidence", "Turn risk into acceptance criteria", "Build a phased scope"] },
  { slug: "fuel-retail-platform-blueprint", kind: "Whitepaper", title: "Fuel Retail Platform Architecture Blueprint", description: "A reference architecture for billing, shifts, wet-stock, credit, reconciliation, and offline continuity.", readTime: "15 min", sections: ["Operational domain boundaries", "Forecourt billing continuity", "Shift and stock reconciliation", "Audit evidence", "Deployment and support model"] },
  { slug: "enterprise-saas-readiness", kind: "Whitepaper", title: "Enterprise SaaS Readiness", description: "A technical checklist for tenancy, permissions, security, observability, support, and commercial scale.", readTime: "14 min", sections: ["Tenant and identity boundaries", "Permission architecture", "Security and audit controls", "Billing and integrations", "Support operations and observability"] },
] as const;
