"use client";
import type { DocumentRecord, Expense, ForgeRole, Lead, Meeting, NotificationRecord, Project, Task } from "@/lib/forgeosData";
import { useForgeOS } from "@/components/forgeos/ForgeOSShell";
import { BurnRateWidget, CashPositionWidget, MonthlyExpensesWidget, PendingPaymentsWidget, RevenueOverviewWidget } from "@/components/forgeos/finance";
import { NotificationRow, PageHeading, SectionLoading, money, panelClass } from "@/components/forgeos/ui";
import { useApiData } from "@/components/forgeos/useApiData";
function dateKey(value: string) { return value.match(/^(\d{4}-\d{2}-\d{2})/)?.[1] || ""; }
export default function DashboardPage() {
  const { role, user } = useForgeOS(); const leadership = ["CEO", "COO"].includes(role); const financeAccess = ["CEO", "CTO"].includes(role);
  const { data: projects, loading: projectsLoading } = useApiData<Project[]>("/api/forgeos/projects", []);
  const { data: tasks, loading: tasksLoading } = useApiData<Task[]>("/api/forgeos/tasks", []);
  const { data: leads, loading: leadsLoading } = useApiData<Lead[]>("/api/forgeos/crm", [], undefined, leadership);
  const { data: expenses, loading: expensesLoading } = useApiData<Expense[]>("/api/forgeos/expenses", [], undefined, financeAccess);
  const { data: documents, loading: documentsLoading } = useApiData<DocumentRecord[]>("/api/forgeos/documents", []);
  const { data: meetings, loading: meetingsLoading } = useApiData<Meeting[]>("/api/forgeos/meetings", []);
  const { data: notifications, loading: notificationsLoading } = useApiData<NotificationRecord[]>("/api/forgeos/notifications", []);
  if (projectsLoading || tasksLoading || leadsLoading || expensesLoading || documentsLoading || meetingsLoading || notificationsLoading) return <><PageHeading title="Dashboard" description="Live company and workspace metrics." /><SectionLoading label="Loading dashboard" /></>;
  const visibleTasks = role === "Employee" ? tasks.filter((task) => task.assignee === user.name) : tasks;
  const today = new Date().toISOString().slice(0, 10); const open = visibleTasks.filter((task) => task.status !== "Done"); const done = visibleTasks.filter((task) => task.status === "Done"); const blocked = visibleTasks.filter((task) => task.status === "Blocked"); const overdue = open.filter((task) => task.dueDate && task.dueDate < today); const activeProjects = projects.filter((project) => project.status === "Active"); const upcoming = meetings.filter((meeting) => dateKey(meeting.when) >= today); const pipeline = leads.reduce((sum, lead) => sum + lead.value, 0); const expenseTotal = expenses.reduce((sum, expense) => sum + expense.amount, 0); const pending = expenses.filter((expense) => ["Submitted", "In review"].includes(expense.status));
  const metrics: Record<ForgeRole, Array<{ label: string; value: string | number }>> = {
    CEO: [{ label: "Active Projects", value: activeProjects.length }, { label: "Open Tasks", value: open.length }, { label: "CRM Leads", value: leads.length }, { label: "Sales Pipeline", value: money(pipeline) }, { label: "Total Expenses", value: money(expenseTotal) }, { label: "Pending Expenses", value: pending.length }, { label: "Upcoming Meetings", value: upcoming.length }, { label: "Unread Notifications", value: notifications.length }],
    CTO: [{ label: "Active Projects", value: activeProjects.length }, { label: "Open Tasks", value: open.length }, { label: "Blocked Tasks", value: blocked.length }, { label: "Completed Tasks", value: done.length }, { label: "Overdue Tasks", value: overdue.length }, { label: "Documents", value: documents.length }, { label: "Upcoming Meetings", value: upcoming.length }, { label: "Unread Notifications", value: notifications.length }],
    COO: [{ label: "Active Projects", value: activeProjects.length }, { label: "Open Tasks", value: open.length }, { label: "CRM Leads", value: leads.length }, { label: "Sales Pipeline", value: money(pipeline) }, { label: "Completed Tasks", value: done.length }, { label: "Documents", value: documents.length }, { label: "Upcoming Meetings", value: upcoming.length }, { label: "Unread Notifications", value: notifications.length }],
    Employee: [{ label: "Assigned Tasks", value: visibleTasks.length }, { label: "Open Tasks", value: open.length }, { label: "Completed Tasks", value: done.length }, { label: "Overdue Tasks", value: overdue.length }, { label: "Active Projects", value: activeProjects.length }, { label: "Documents", value: documents.length }, { label: "Upcoming Meetings", value: upcoming.length }, { label: "Unread Notifications", value: notifications.length }],
  };
  return <><PageHeading title="Dashboard" description="Live company and workspace metrics." /><div className="grid gap-7 xl:grid-cols-[1.2fr_0.8fr]"><section className={panelClass}><h3 className="mb-5 text-xl font-medium">Live Metrics</h3><div className="grid gap-3.5 sm:grid-cols-2 xl:grid-cols-3">{metrics[role].map((metric) => <div key={metric.label} className="rounded-lg border border-[#121212]/10 bg-[#F7F7F5] p-5"><p className="text-sm font-medium">{metric.label}</p><p className="mt-2 text-2xl font-semibold">{metric.value}</p></div>)}</div></section><section className={panelClass}><h3 className="mb-5 text-xl font-medium">Recent Activity</h3><div className="grid gap-3.5">{notifications.length ? notifications.slice(0, 6).map((item) => <NotificationRow key={item.id} item={item} />) : <p className="text-sm text-[#121212]/50">No recent activity.</p>}</div></section></div>{financeAccess && <><h3 className="mb-4 mt-8 text-xl font-medium">Finance Overview</h3><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><RevenueOverviewWidget /><MonthlyExpensesWidget expenses={expenses} /><CashPositionWidget /><BurnRateWidget expenses={expenses} /><PendingPaymentsWidget projects={projects} /></div></>}</>;
}
