import { NextResponse } from "next/server";
import { isDateBlocked } from "@/lib/blockedDates";
import { readBlockedDates } from "@/lib/forgeosBlockedDates";
import { getAdminSession, hasAdminAuthConfig, missingAdminAuthConfigMessage } from "@/lib/adminAuth";
import { createForgeLead, readForgeLeads, type LeadInput } from "@/lib/forgeosCRM";
import { createForgeNotification } from "@/lib/forgeosNotifications";
const unauthorized = () => NextResponse.json({ error: "Please login from ForgeOS first." }, { status: 401 });
export async function GET(request: Request) { if (!hasAdminAuthConfig()) return NextResponse.json({ error: missingAdminAuthConfigMessage() }, { status: 500 }); const session = getAdminSession(request); if (!session) return unauthorized(); if (!["CEO", "COO"].includes(session.role)) return NextResponse.json({ error: "CRM access is restricted." }, { status: 403 }); try { return NextResponse.json({ leads: await readForgeLeads() }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to load leads." }, { status: 500 }); } }
export async function POST(request: Request) { if (!hasAdminAuthConfig()) return NextResponse.json({ error: missingAdminAuthConfigMessage() }, { status: 500 }); const session = getAdminSession(request); if (!session) return unauthorized(); if (!["CEO", "COO"].includes(session.role)) return NextResponse.json({ error: "CRM access is restricted." }, { status: 403 }); const body = (await request.json()) as Partial<LeadInput>; if (!body.company || !body.contact) return NextResponse.json({ error: "Company and contact name are required." }, { status: 400 }); try { const blocked = isDateBlocked(body.nextFollowUp || "", await readBlockedDates()); if (blocked) return NextResponse.json({ error: `This date falls in a blocked period: ${blocked.reason}` }, { status: 400 }); const lead = await createForgeLead({ company: body.company, contact: body.contact, email: body.email || "", phone: body.phone || "", source: body.source || "Website", stage: "New", owner: `${session.name} (${session.role})`, value: body.value || 0, nextFollowUp: body.nextFollowUp || "", notes: body.notes || "" }); await createForgeNotification({ title: "New CRM lead", body: `${lead.company} was added to the CRM pipeline.`, type: "CRM", recipientRole: session.role === "CEO" ? "COO" : "CEO", recipientEmail: "", linkedModule: "crm", linkedRecordId: lead.id }).catch(() => undefined); return NextResponse.json({ lead }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to create lead." }, { status: 500 }); } }
